# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

r_check_args: '--as-cran --use-valgrind'

addons:
  apt:
    packages:
      - valgrind

before_install:
  - echo '--leak-check=full' > ~/.valgrindrc
  - echo '--track-origins=yes' >> ~/.valgrindrc

cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
